### ISSUE TITLE
Multiple tonic widgets

### ISSUE THREAD

**Issue by rob-tench** [designmynight/designmynight-developers#22]
Hi, I'm trying to set up two tonic widgets on the same page with the code below, for a simple widget

```<!-- START DesignMyNight event widget -->
<script src="//partners.designmynight.com/pw?v=3&r=1000" item-ids="546a14bc0df690b92489b1a7" ></script>

<script src="//partners.designmynight.com/pw?v=3&r=2000" item-ids="546a14bc0df690b92489b1a7" ></script>
```

But that doesn't seem to work, only one widget is displayed. With the collins, we could achieve this by specifying a random param in the script src, which allowed multiple widgets on the same page. Is this still possible with the tonic widget?

Thanks :)

**Comment by rob-tench** [comment]
Anyone? :D

**Comment by jmosul** [comment]
Hi @rob-tench 

Sorry for the delay

Unfortunately this is not possible on the Tonic ticket widget right now.  We do however have a new widget in the works which will be able to do this without specifying a random param.  Though I'm unable to give an ETA on that yet.

Your option for multiple widgets on one page is to wrap at least one of them in an iframe.

If you're looking to show different events on one page, I noticed your event is in an Event Brand.  You can instead use the Widget Wizard in https://admin.designmynight.com/events/brands to generate a widget to show all your Event brand's event.
Or you can list multiple event ids in the same widget as described in the docs http://developers.designmynight.com/tonic/ticket-widget/


Another option some other organisers have used is the 'Modal Mode' which places the widget in a modal with a "Buy Now" button being shown where you place the script tag.

Then by adding the following code
```html
<script type="application/javascript">
  var triggerButtons = document.getElementsByClassName('tw-modal-trigger');

  for(var i=0; i < triggerButtons.length; i++){
    triggerButtons[i].addEventListener("click", function(e) {
      document.querySelector('button[ng-click="tonicWidgetConfig.showTicketWidget = !tonicWidgetConfig.showTicketWidget"]').click();
    }, false);
  }
</script>
```

You can place as many of the following buttons as you wish across the page.  They will all trigger the same widget to open

```html
<button type="button" class="tw-btn tw-btn--primary tw-btn--lg tw-modal-trigger" title="Open Buy Tickets">Buy Tickets</button>
```

Hope this helps

**Comment by rob-tench** [comment]
That's brilliant :) 
Thanks :)
